services: 
  dev_app:
    build: .
    container_name: dev_app
    ports:
      - "8002:8000"
    volumes:
      - ./:/app
    environment:
      - app_state=dev
    working_dir: /app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    # command: fastapi dev main.py --host 0.0.0.0 --port 8000 #tail -f /dev/null
    