services: 
  dev_app:
    build: .
    container_name: dev_app
    ports:
      - "8002:8000"
    volumes:
      - ./:/app
    environment:
      - app_state=dev
    working_dir: /app
    command: fastapi dev main.py --host 0.0.0.0 --port 8000 #tail -f /dev/null
    
  app: 
    build: . 
    ports: 
    - 8003:8000

    environment:
      - app_state=PROD
    working_dir: /app
    volumes: 
    - ./:/app

    command: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app
    # command: uvicorn main:app --host 0.0.0.0 --port 8000
    # fastapi dev main.py --host 0.0.0.0 --port 8000 #tail -f /dev/null
