services: 
  dev_app:
    build: .
    container_name: dev_app
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    working_dir: /app
    command: "fastapi dev main.py"
    
  app: 
    build: . 
    ports: 
    - 8080:8000

    working_dir: /app
    volumes: 
    - ./:/app

    command: fastapi dev main.py #tail -f /dev/null
